spring:
  application:
    name: Trader
  #autoconfigure:
    #exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/andrewdb
    username: andrew
    password: pwd
    driver-class-name: org.postgresql.Driver