spring:
  application:
    name: Trader
  #autoconfigure:
    #exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  #profiles:
    #active: jpa
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

